# Generated by Django 5.1.4 on 2024-12-09 06:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='duration',
            field=models.DurationField(default=datetime.timedelta),
        ),
    ]
