# Generated by Django 5.1.4 on 2024-12-11 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_buses_trains_bus_train'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='airline',
        ),
        migrations.RemoveField(
            model_name='train',
            name='airline',
        ),
        migrations.AddField(
            model_name='bus',
            name='Buses',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='web.buses'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='train',
            name='trains',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='web.trains'),
            preserve_default=False,
        ),
    ]
