# Generated by Django 5.1.4 on 2024-12-11 11:42

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_remove_bus_airline_remove_train_airline_bus_buses_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
                ('discount', models.FloatField()),
                ('short_description', models.CharField(max_length=255)),
                ('is_percentage', models.BooleanField()),
            ],
            options={
                'verbose_name': 'offer',
                'verbose_name_plural': 'offers',
                'db_table': 'offer',
                'ordering': ['-id'],
            },
        ),
        migrations.AlterField(
            model_name='bus',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(seconds=3600)),
        ),
        migrations.AlterField(
            model_name='train',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(seconds=3600)),
        ),
        migrations.CreateModel(
            name='CartBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_total', models.FloatField()),
                ('offer_amount', models.FloatField()),
                ('totel_amount', models.FloatField()),
                ('tax_charge', models.FloatField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.customer')),
            ],
            options={
                'verbose_name': 'cartbill',
                'verbose_name_plural': 'cartbills',
                'db_table': 'customer_cartbill',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='FlightBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airline_name', models.CharField(max_length=255)),
                ('flight_code', models.CharField(max_length=50)),
                ('departure_time', models.TimeField()),
                ('arrival_time', models.TimeField()),
                ('duration', models.CharField(max_length=50)),
                ('departure_airport', models.CharField(max_length=255)),
                ('arrival_airport', models.CharField(max_length=255)),
                ('baggage_allowance', models.CharField(max_length=50)),
                ('cabin_baggage', models.CharField(max_length=50)),
                ('check_in_baggage', models.CharField(max_length=50)),
                ('terminal', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(max_length=100)),
                ('fligths', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.flight')),
            ],
        ),
    ]
