# Generated by Django 5.1.4 on 2024-12-12 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_offer_alter_bus_duration_alter_train_duration_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bus',
            old_name='Buses',
            new_name='buses',
        ),
        migrations.CreateModel(
            name='BusDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_name', models.CharField(max_length=255)),
                ('bus_code', models.CharField(max_length=50)),
                ('departure_time', models.TimeField()),
                ('arrival_time', models.TimeField()),
                ('duration', models.CharField(max_length=50)),
                ('departure_stop', models.CharField(max_length=255)),
                ('arrival_stop', models.CharField(max_length=255)),
                ('baggage_allowance', models.CharField(max_length=50)),
                ('cabin_baggage', models.CharField(max_length=50)),
                ('check_in_baggage', models.CharField(max_length=50)),
                ('terminal', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(max_length=100)),
                ('buses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.bus')),
            ],
        ),
        migrations.CreateModel(
            name='TrainDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_name', models.CharField(max_length=255)),
                ('train_code', models.CharField(max_length=50)),
                ('departure_time', models.TimeField()),
                ('arrival_time', models.TimeField()),
                ('duration', models.CharField(max_length=50)),
                ('departure_stop', models.CharField(max_length=255)),
                ('arrival_stop', models.CharField(max_length=255)),
                ('baggage_allowance', models.CharField(max_length=50)),
                ('cabin_baggage', models.CharField(max_length=50)),
                ('check_in_baggage', models.CharField(max_length=50)),
                ('terminal', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(max_length=100)),
                ('trains', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.train')),
            ],
        ),
    ]
