# Generated by Django 5.1.4 on 2024-12-17 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_rename_buses_bus_buses_busdetail_traindetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusSeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(max_length=10)),
                ('seat_type', models.CharField(choices=[('upper', 'Upper'), ('lower', 'Lower')], max_length=10)),
                ('status', models.CharField(choices=[('available', 'Available'), ('booked', 'Booked')], default='available', max_length=10)),
                ('Buses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='web.bus')),
            ],
        ),
    ]
