# Generated by Django 5.1.4 on 2024-12-17 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_busseat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='busseat',
            old_name='Buses',
            new_name='buses',
        ),
    ]
