# Generated by Django 5.1.4 on 2024-12-18 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_rename_buses_busseat_buses'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='total_seat',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='BusSeatStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_side', models.CharField(choices=[('A', 'Side A'), ('B', 'Side B')], default='A', max_length=1)),
                ('seat_number', models.IntegerField()),
                ('status', models.CharField(choices=[('available', 'Available'), ('booked', 'Booked')], default='available', max_length=10)),
                ('buses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.bus')),
            ],
            options={
                'ordering': ['seat_side', 'seat_number'],
            },
        ),
        migrations.DeleteModel(
            name='BusSeat',
        ),
    ]
