# Generated by Django 5.1.4 on 2024-12-30 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_bus_arrival_name_bus_departure_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='train',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
