# Generated by Django 5.1.4 on 2025-01-02 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_travelclassprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='discount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bus',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='flight',
            name='discount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='train',
            name='discount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='train',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='travelclassprice',
            name='price',
            field=models.FloatField(verbose_name='Price'),
        ),
    ]
