# Generated by Django 5.1.4 on 2025-01-06 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_alter_bus_discount_alter_bus_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelclassprice',
            name='airline',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='web.airlines'),
            preserve_default=False,
        ),
    ]
