# Generated by Django 5.1.4 on 2025-01-06 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_travelclassprice_airline'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartbill',
            name='adults',
            field=models.PositiveIntegerField(default=1, help_text='Number of adults'),
        ),
        migrations.AddField(
            model_name='cartbill',
            name='children',
            field=models.PositiveIntegerField(default=0, help_text='Number of children'),
        ),
        migrations.AddField(
            model_name='cartbill',
            name='infants',
            field=models.PositiveIntegerField(default=0, help_text='Number of infants'),
        ),
        migrations.AlterField(
            model_name='travelclassprice',
            name='travel_class',
            field=models.CharField(choices=[('economy', 'Economy'), ('premium-economy', 'Premium Economy'), ('business', 'Business'), ('first-class', 'First Class')], max_length=20, verbose_name='Travel Class'),
        ),
    ]
