# Generated by Django 5.1.4 on 2025-01-15 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_cartbill_offer_code_alter_cartbill_offer_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightbill',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='web.customer'),
            preserve_default=False,
        ),
    ]
