# Generated by Django 5.1.4 on 2025-01-15 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_flightbill_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightbill',
            name='travel_class_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
